# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MerlinMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MerlinMobile
  pod 'React', :path => '../node_modules/react-native'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'


  target 'MerlinMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MerlinMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MerlinMobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MerlinMobile-tvOS

  target 'MerlinMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
