# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hallmarkAppFront' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hallmarkAppFront
  pod 'React', :path => '../node_modules/react-native'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'


  target 'hallmarkAppFront-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'hallmarkAppFrontTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'hallmarkAppFront-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hallmarkAppFront-tvOS

  target 'hallmarkAppFront-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
